<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>doshik</string>
   </array>
  <key>name</key>
  <string>doshik</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.doshik</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.line.double-slash.doshik</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.quoted.double.doshik</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.quoted.double.doshik</string>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.quoted.double.doshik</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(default|new|event|private|public|out|if|else|while|for|break|continue|return)</string>
          <key>name</key>
          <string>keyword.other.doshik</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(bool|byte|sbyte|char|decimal|double|float|int|uint|long|ulong|short|ushort|object|string|void)</string>
          <key>name</key>
          <string>keyword.other.doshik</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(true|false|null)</string>
          <key>name</key>
          <string>keyword.other.doshik</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(0[xX](?:(?:[0-9a-fA-F])+))</string>
          <key>name</key>
          <string>constant.numeric.doshik</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:(?:[0-9])+)\.(?:(?:[0-9])+)(?:[fd])?)</string>
          <key>name</key>
          <string>constant.numeric.doshik</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:[0-9])+)</string>
          <key>name</key>
          <string>constant.numeric.doshik</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:\:\:)|(?:\.)|(?:\;)|(?:\,)|(?:\()|(?:\))|(?:\{)|(?:\})|(?:\[)|(?:\]))</string>
          <key>name</key>
          <string>punctuation.doshik</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:[a-zA-Z_])(?:(?:[a-zA-Z_])|(?:[0-9]))*)</string>
          <key>name</key>
          <string>variable.other.doshik</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.doshik</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.block.doshik</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.doshik</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
  </dict>
</dict>
</plist>
