//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\Programs\DoshikLang\DoshikLangAntlr\DoshikParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DoshikParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IDoshikParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilationUnit([NotNull] DoshikParser.CompilationUnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaration([NotNull] DoshikParser.MemberDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDeclaration([NotNull] DoshikParser.MethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.typeTypeOrVoid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeTypeOrVoid([NotNull] DoshikParser.TypeTypeOrVoidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDeclaration([NotNull] DoshikParser.FieldDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarator([NotNull] DoshikParser.VariableDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableInitializer([NotNull] DoshikParser.VariableInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInitializer([NotNull] DoshikParser.ArrayInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassOrInterfaceType([NotNull] DoshikParser.ClassOrInterfaceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.typeArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArgument([NotNull] DoshikParser.TypeArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameters([NotNull] DoshikParser.FormalParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameterList([NotNull] DoshikParser.FormalParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameter([NotNull] DoshikParser.FormalParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] DoshikParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerLiteral([NotNull] DoshikParser.IntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] DoshikParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatement([NotNull] DoshikParser.BlockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVariableDeclaration([NotNull] DoshikParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] DoshikParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForControl([NotNull] DoshikParser.ForControlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInit([NotNull] DoshikParser.ForInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.parExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParExpression([NotNull] DoshikParser.ParExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] DoshikParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall([NotNull] DoshikParser.MethodCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.methodCallParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallParams([NotNull] DoshikParser.MethodCallParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.methodCallParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallParam([NotNull] DoshikParser.MethodCallParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.newCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewCall([NotNull] DoshikParser.NewCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.newConstCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewConstCall([NotNull] DoshikParser.NewConstCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.newConstCallParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewConstCallParams([NotNull] DoshikParser.NewConstCallParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.newConstCallParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewConstCallParam([NotNull] DoshikParser.NewConstCallParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.constExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstExpression([NotNull] DoshikParser.ConstExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.constArrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstArrayInitializer([NotNull] DoshikParser.ConstArrayInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>primaryExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] DoshikParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>newCallExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewCallExpression([NotNull] DoshikParser.NewCallExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>dotExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDotExpression([NotNull] DoshikParser.DotExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>additionExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditionExpression([NotNull] DoshikParser.AdditionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryPrefixExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryPrefixExpression([NotNull] DoshikParser.UnaryPrefixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>newConstCallExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewConstCallExpression([NotNull] DoshikParser.NewConstCallExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>methodCallExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCallExpression([NotNull] DoshikParser.MethodCallExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>assignmentExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpression([NotNull] DoshikParser.AssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bracketsExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracketsExpression([NotNull] DoshikParser.BracketsExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpression([NotNull] DoshikParser.NotExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multiplicationExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicationExpression([NotNull] DoshikParser.MultiplicationExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryPostfixExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryPostfixExpression([NotNull] DoshikParser.UnaryPostfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>relativeExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelativeExpression([NotNull] DoshikParser.RelativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifElseExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseExpression([NotNull] DoshikParser.IfElseExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>orExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpression([NotNull] DoshikParser.OrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>andExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] DoshikParser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>equalsExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualsExpression([NotNull] DoshikParser.EqualsExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typecastExpression</c>
	/// labeled alternative in <see cref="DoshikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypecastExpression([NotNull] DoshikParser.TypecastExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenthesisExpression</c>
	/// labeled alternative in <see cref="DoshikParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExpression([NotNull] DoshikParser.ParenthesisExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literalExpression</c>
	/// labeled alternative in <see cref="DoshikParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralExpression([NotNull] DoshikParser.LiteralExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="DoshikParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierExpression([NotNull] DoshikParser.IdentifierExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.typeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeType([NotNull] DoshikParser.TypeTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveType([NotNull] DoshikParser.PrimitiveTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DoshikParser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArguments([NotNull] DoshikParser.TypeArgumentsContext context);
}
